"Set up Pathogen
call pathogen#infect() 



" Set preferences for Gundo
" Use F5 key to toggle on the sidebar
nnoremap  :GundoToggle<CR>
" Make the preview area show up down the bottom of the main window instead of the bottom of the sidebar
"  - means there's more room to see the diff
let g:gundo_preview_bottom = 1
" Make the sidebar disappear when a selection to revert to is made.
let g:gundo_close_on_revert = 1
" Open GUndo on the right hand side (leaving NERDTree on the left - other wise nerd tree's width gets stuck when dismissing undo window)
let g:gundo_right = 1



" Basic familiarities
set autoindent
set ruler
set number
set mouse=a
" set ai ru nu mouse=a

syntax on


" Solarized theme
syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized


" Customisations courtesy of http://nvie.com/posts/how-i-boosted-my-vim/
" .swp files
set nobackup
set noswapfile

" 
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep


set nowrap        " don't wrap lines
set tabstop=4     " a tab is four spaces
set backspace=indent,eol,start

" allow backspacing over everything in insert mode
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set number        " always show line numbers
set shiftwidth=4  " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,

"    case-sensitive otherwise
set smarttab      " insert tabs on the start of a line according to

"    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l


" Basic key remappings.
" - Get used to not using the arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" - Go to the next line in the display, not the next line of the file - eg for wrapped lines
nnoremap j gj
nnoremap k gk

" NERDTree (with tabs)
nnoremap <F2> :NERDTreeTabsToggle<CR>
let g:nerdtree_tabs_open_on_console_startup=1

